# Docker Infrastructure
sudo: false
bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem update bundler

language: ruby
rvm:
  - 2.3.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
