sudo: false
bundler_args: "--jobs=3 --retry=3"
cache: bundler
env:
  global:
  - secure: UdVkFD3qu/BNy6MQN38Csy3DD58vnFXttCbwgdWvZJZ5m87LMwfbGopG50VcUEurrUlL0s/bY1BsWfm7PaW60dBF1ReEOuTIE/Ys1WQ34FOP2HqRMtBtJiZLAT6YOK3riwRMcnRvy4Fpqy3+T45Swqi8OIKDfh0jpYt6WBk6DrrnRWRljbQVE5WDfacan7V2Xilz4Y8gt1x38jn2XmTFzCX8zWnHkveSvJdaWadqlMzc6rdcEUGuiJDZsyITaPPibKRVxM73hfY4tx90BianLWjPArqoHw/IUdcFzlrHNpT67ugLEM9LxopvxfUcuibPuElXQ5nikhQkxlOo8Xos0KbQAURnlFizib14+6MObXa4aSk6T09AsTcvP7bxmWxlPhycJtch+ft/8Ey3y/yC76a3PSpo7/ZxhfDYEk6IXZXI/pOXZ6A7XQ+D4XL/mgraKJlonVITap4erpbCpFMiXAQvQcS3gxW5THK3S8q2YTfmvBgM3A8tM8YVrlsNFrbVWo9TuWlmJEm104c1nWH/9NygRnUqjq+a6yNXTNkLManuZqUED/leQw1Y3FUtJrBTQ2BeeD/7E0C1e7H09VhyXO0AnoGUbPtod6qhpXpMPFro/NRZ7/kV882lCQYXIWnPWvEO3gd/3bd6R44PoPZMfSgvlk+9Ovf7ZZiG0HhT9XU=
  - secure: jRIZKzHqzrT48s3C6+J2qJexI8pENLScktJkBMJpno5aRqOX6hJYJ5CtjUVT8V7cxe0CzSl9KMpgzH/s8pg1w9Qgps9L1STQc35iNveZPM0xBju/K2HdV3fnyAL2fe0TqKwtbdek9OkODa0Q4Y+PkZXaeCEjAMDhmxkcq3/Tpa+9c+lOksdS64fV8ncCxW1t/qjqqjEydq8rqo1qxtt4pmk0eJ2CN38ZNpdSOKj91QXJQbauzUbWAnrcNjV183jD1ByaJnhb2rlxybtDlzkAxQW0wWAmrM2lKmzRsGIaW4PQN2cPFaG5cjVaHU41+O4MS/SaS3jVcJtNy3U3hQzpCf5OP4Q8VTgNGuU3T2wcBNfccf9t+fH424YvNiMbj+vZcNZbzefU9IoDrpPNfgLW8BngFA6xzJvKmB3Kg9ZKptEU4/dCFKiOG+IUgiALxfa1Q6gTvu+tRwLYeiCdt2h1zn80GJcboWWgSrLg8X8DTXdJuSdny/O6kPtPrQLBUu0X7f5MmW/77Sque7YLc5PY/yqPTUJnNwb3rLLmoUZqSWmSGsMSylERuRanhX9v4xSDmMNXPAT3KV/cza5AvxGkuMua6JWkMISUkkhfuqOsChWT6l2hWfsi1B40MkK6I7cgWWUDJM/UnWoZ+vJkC18NJLmC0clyoYPYRk1surahQrs=
  - secure: sym4vL38op7F1qygpQPdlIbF4a4JyfBGKP81QWsGqFCeSlVOeV1tGvWuCOm/lD2QMgc3z8xDo5QZfR4rXXQ8RmXMzkQf4E4frq6Qi27/E1md+BpPj3+fkQUV2kbi3D0dgKXgotPG6qedQ1g6ef5mhpr9ahTLAPJJ8ytb0IGYiwQpecM/OSNPA+rZr6ADyajO2SIVjavcGEWMebAadgm7cy0VCsIk3ymr8k0Dsl0KSDfqFzRaq4lqxsxQn0jAUvjZdjnaOn1l7WV91w0tIEZWXDPkpLxc1smB1b4u7ldazRcEXKG437OiM39yuA31VgIKs9zbj0HcZT+bsKI+TTB/jfBiNiB1lSO2H1mlkf/LNN4TQpahg9f7THl79GemWHtKI9XOfBaBvea0lsnzCfoKDdk9waWiGZftNuWJOm6Cp9CJT+r/KDCTcna/gnxpMXGuN/4Mpi8Sj9sQuoQUlH11v2Qn351qXBrcG8RDOIx8IeYSbNieoogIc5SgG/elpAowiYtDAyc9d32dlvHoukRZCJePuSHFY691/3arOko47RCeb1VPOGf7E3k0RnRgvfrHgVV0F0+3rnRy0RD39bl202GrbmgzHHvN4f/wmlNxzt0ahOxYVJiffuhqTaO1tjtbOT54nKVM6IOinP5sSePZbDZUudrvodFnT1rafkn0xSY=
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - gem update bundler
language: ruby
rvm:
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
